app:
  title: zhaoyss-spring
  version: 1.0.0
zhaoyss:
  datasource:
      url: jdbc:sqlite:test.db
      driver-class-name: org.sqlite.JDBC
      username: sa
      password:
other:
  deep:
    deep:
      level: level-4
  hex-data: 0x1a2b3c
  hex-string: "0x1a2b3c"