server:
  port: ${PORT:8080}

app:
  title: Hello Applicaiton
  version: 1.0

zhaoyss:
  datasource:
    url: jdbc:sqlite:helloboottestdb.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
